### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#417]
```
[03:01:15.564] Running build in San Francisco, USA (West) – sfo1
[03:01:15.624] Cloning github.com/CorrelAid/correlaid_website (Branch: main, Commit: 40e83b9)
[03:01:16.437] Cloning completed: 812.347ms
[03:01:16.437] Running "[ "$VERCEL_ENV" != production ]"
[03:01:16.451] Warning: Detected "engines": { "node": "^16.14 || >=18" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[03:01:16.985] Restored build cache
[03:01:17.017] Running "vercel build"
[03:01:17.535] Vercel CLI 29.3.6
[03:01:18.141] Warning: Detected "engines": { "node": "^16.14 || >=18" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[03:01:18.150] Running "install" command: `npm install`...
[03:01:19.738] 
[03:01:19.738] up to date, audited 721 packages in 1s
[03:01:19.739] 
[03:01:19.739] 148 packages are looking for funding
[03:01:19.739]   run `npm fund` for details
[03:01:19.740] 
[03:01:19.740] found 0 vulnerabilities
[03:01:20.129] 
[03:01:20.129] > correlaid-org@0.0.1 build
[03:01:20.129] > vite build
[03:01:20.129] 
[03:01:20.594] ADAPTER:  STATIC  PRERENDER:  ALL
[03:01:22.553] 
[03:01:22.554] [36mvite v4.3.6 [32mbuilding SSR bundle for production...[36m[39m
[03:01:22.688] transforming...
[03:01:23.751] 
[03:01:23.751] [1m[33mwarn[39m[22m - As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.
[03:01:23.751] [1m[33mwarn[39m[22m - Remove it from the `plugins` array in your configuration to eliminate this warning.
[03:01:25.608] [32m✓[39m 241 modules transformed.
[03:01:25.730] rendering chunks...
[03:01:26.285] ADAPTER:  STATIC  PRERENDER:  ALL
[03:01:27.933] ADAPTER:  STATIC  PRERENDER:  ALL
[03:01:29.195] 
[03:01:29.196] [36mvite v4.3.6 [32mbuilding for production...[36m[39m
[03:01:29.212] transforming...
[03:01:36.746] [32m✓[39m 438 modules transformed.
[03:01:37.027] rendering chunks...
[03:01:37.680] computing gzip size...
[03:01:37.783] [2m.svelte-kit/output/client/[22m[32m_app/version.json                                 [39m[1m[2m  0.03 kB[22m[1m[22m[2m │ gzip:   0.05 kB[22m
[03:01:37.783] [2m.svelte-kit/output/client/[22m[32mvite-manifest.json                                [39m[1m[2m 18.88 kB[22m[1m[22m[2m │ gzip:   1.71 kB[22m
[03:01:37.783] [2m.svelte-kit/output/client/[22m[35m_app/immutable/assets/Html.a396058f.css           [39m[1m[2m  1.47 kB[22m[1m[22m[2m │ gzip:   0.66 kB[22m
[03:01:37.783] [2m.svelte-kit/output/client/[22m[35m_app/immutable/assets/0.7d78d2c5.css              [39m[1m[2m 43.30 kB[22m[1m[22m[2m │ gzip:   8.20 kB[22m
[03:01:37.783] [2m.svelte-kit/output/client/[22m[35m_app/immutable/assets/28.143464c5.css             [39m[1m[2m 70.51 kB[22m[1m[22m[2m │ gzip:   9.65 kB[22m
[03:01:37.784] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/page_key.954543c5.js        [39m[1m[2m  0.08 kB[22m[1m[22m[2m │ gzip:   0.10 kB[22m
[03:01:37.784] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/i18n.61512e87.js            [39m[1m[2m  0.15 kB[22m[1m[22m[2m │ gzip:   0.14 kB[22m
[03:01:37.784] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/stores.640e92c3.js          [39m[1m[2m  0.27 kB[22m[1m[22m[2m │ gzip:   0.18 kB[22m
[03:01:37.784] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/24.a74c0e62.js               [39m[1m[2m  0.31 kB[22m[1m[22m[2m │ gzip:   0.24 kB[22m
[03:01:37.784] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/23.ed9e4892.js               [39m[1m[2m  0.31 kB[22m[1m[22m[2m │ gzip:   0.24 kB[22m
[03:01:37.784] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/15.61aa8e4d.js               [39m[1m[2m  0.31 kB[22m[1m[22m[2m │ gzip:   0.24 kB[22m
[03:01:37.785] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/8.fbb1625e.js                [39m[1m[2m  0.31 kB[22m[1m[22m[2m │ gzip:   0.25 kB[22m
[03:01:37.785] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/25.09c6aa7f.js               [39m[1m[2m  0.31 kB[22m[1m[22m[2m │ gzip:   0.25 kB[22m
[03:01:37.785] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/16.6b4dcedb.js               [39m[1m[2m  0.31 kB[22m[1m[22m[2m │ gzip:   0.25 kB[22m
[03:01:37.785] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/31.3092a6d0.js               [39m[1m[2m  0.31 kB[22m[1m[22m[2m │ gzip:   0.25 kB[22m
[03:01:37.785] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/11.4faa5827.js               [39m[1m[2m  0.32 kB[22m[1m[22m[2m │ gzip:   0.25 kB[22m
[03:01:37.786] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/9.eaec8e01.js                [39m[1m[2m  0.32 kB[22m[1m[22m[2m │ gzip:   0.25 kB[22m
[03:01:37.786] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/18.309bfa6f.js               [39m[1m[2m  0.32 kB[22m[1m[22m[2m │ gzip:   0.26 kB[22m
[03:01:37.786] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/27.7594f90f.js               [39m[1m[2m  0.32 kB[22m[1m[22m[2m │ gzip:   0.26 kB[22m
[03:01:37.786] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/12.9ff333d4.js               [39m[1m[2m  0.33 kB[22m[1m[22m[2m │ gzip:   0.25 kB[22m
[03:01:37.786] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/26.7bf36efd.js               [39m[1m[2m  0.33 kB[22m[1m[22m[2m │ gzip:   0.26 kB[22m
[03:01:37.787] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/30.02fecb9c.js               [39m[1m[2m  0.33 kB[22m[1m[22m[2m │ gzip:   0.26 kB[22m
[03:01:37.787] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/1.0ec90272.js                [39m[1m[2m  0.80 kB[22m[1m[22m[2m │ gzip:   0.50 kB[22m
[03:01:37.787] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/index.63293b21.js           [39m[1m[2m  0.82 kB[22m[1m[22m[2m │ gzip:   0.50 kB[22m
[03:01:37.787] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/3.333ca3b9.js                [39m[1m[2m  0.91 kB[22m[1m[22m[2m │ gzip:   0.60 kB[22m
[03:01:37.787] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/External_Link.ca893910.js   [39m[1m[2m  1.14 kB[22m[1m[22m[2m │ gzip:   0.62 kB[22m
[03:01:37.788] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/13.284015d5.js               [39m[1m[2m  1.75 kB[22m[1m[22m[2m │ gzip:   0.94 kB[22m
[03:01:37.788] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/19.05efa96f.js               [39m[1m[2m  1.78 kB[22m[1m[22m[2m │ gzip:   0.95 kB[22m
[03:01:37.788] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/17.e2b2e666.js               [39m[1m[2m  1.80 kB[22m[1m[22m[2m │ gzip:   0.98 kB[22m
[03:01:37.788] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/6.9aaef045.js                [39m[1m[2m  1.81 kB[22m[1m[22m[2m │ gzip:   0.99 kB[22m
[03:01:37.788] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/32.fffec37e.js               [39m[1m[2m  1.91 kB[22m[1m[22m[2m │ gzip:   1.03 kB[22m
[03:01:37.788] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/21.42362925.js               [39m[1m[2m  1.96 kB[22m[1m[22m[2m │ gzip:   1.02 kB[22m
[03:01:37.789] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Box.cf0f4a46.js             [39m[1m[2m  2.18 kB[22m[1m[22m[2m │ gzip:   0.90 kB[22m
[03:01:37.789] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/singletons.0fe69597.js      [39m[1m[2m  2.50 kB[22m[1m[22m[2m │ gzip:   1.26 kB[22m
[03:01:37.789] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/ProjectLinks.990b1a62.js    [39m[1m[2m  2.70 kB[22m[1m[22m[2m │ gzip:   1.06 kB[22m
[03:01:37.789] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Events_Card.cacf292d.js     [39m[1m[2m  3.44 kB[22m[1m[22m[2m │ gzip:   1.72 kB[22m
[03:01:37.789] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Text_Container.b05db322.js  [39m[1m[2m  3.51 kB[22m[1m[22m[2m │ gzip:   1.59 kB[22m
[03:01:37.789] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/EN.6cff5baf.js              [39m[1m[2m  3.62 kB[22m[1m[22m[2m │ gzip:   1.11 kB[22m
[03:01:37.790] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/7.37b9ec5e.js                [39m[1m[2m  3.66 kB[22m[1m[22m[2m │ gzip:   1.48 kB[22m
[03:01:37.790] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/22.0d1248ea.js               [39m[1m[2m  5.08 kB[22m[1m[22m[2m │ gzip:   2.14 kB[22m
[03:01:37.790] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/5.aaec0484.js                [39m[1m[2m  5.24 kB[22m[1m[22m[2m │ gzip:   2.09 kB[22m
[03:01:37.790] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/20.8b0bb5ac.js               [39m[1m[2m  5.27 kB[22m[1m[22m[2m │ gzip:   2.15 kB[22m
[03:01:37.790] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/2.464a4d21.js                [39m[1m[2m  5.60 kB[22m[1m[22m[2m │ gzip:   2.10 kB[22m
[03:01:37.790] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/parse_cms.cb62eda6.js       [39m[1m[2m  6.19 kB[22m[1m[22m[2m │ gzip:   1.90 kB[22m
[03:01:37.791] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/4.312af8a2.js                [39m[1m[2m  6.21 kB[22m[1m[22m[2m │ gzip:   2.30 kB[22m
[03:01:37.792] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Blog_Card.bc54d57f.js       [39m[1m[2m  6.75 kB[22m[1m[22m[2m │ gzip:   2.97 kB[22m
[03:01:37.792] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Person.2e03a5fa.js          [39m[1m[2m  6.98 kB[22m[1m[22m[2m │ gzip:   2.87 kB[22m
[03:01:37.792] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/10.498b9225.js               [39m[1m[2m  7.38 kB[22m[1m[22m[2m │ gzip:   3.01 kB[22m
[03:01:37.792] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/29.6c384878.js               [39m[1m[2m  7.44 kB[22m[1m[22m[2m │ gzip:   2.65 kB[22m
[03:01:37.793] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/ProjectsCard.3fffbd50.js    [39m[1m[2m  7.93 kB[22m[1m[22m[2m │ gzip:   3.40 kB[22m
[03:01:37.793] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Links.c0444d20.js           [39m[1m[2m 11.38 kB[22m[1m[22m[2m │ gzip:   3.94 kB[22m
[03:01:37.793] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/index.1bc45043.js           [39m[1m[2m 13.49 kB[22m[1m[22m[2m │ gzip:   5.76 kB[22m
[03:01:37.793] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Langs.d2f8c087.js           [39m[1m[2m 15.63 kB[22m[1m[22m[2m │ gzip:   5.87 kB[22m
[03:01:37.793] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/14.ea4483b7.js               [39m[1m[2m 16.94 kB[22m[1m[22m[2m │ gzip:   5.35 kB[22m
[03:01:37.793] [2m.svelte-kit/output/client/[22m[36m_app/immutable/entry/app.710ba518.js              [39m[1m[2m 18.10 kB[22m[1m[22m[2m │ gzip:   3.88 kB[22m
[03:01:37.801] [2m.svelte-kit/output/client/[22m[36m_app/immutable/entry/start.755d5e4e.js            [39m[1m[2m 23.88 kB[22m[1m[22m[2m │ gzip:   9.48 kB[22m
[03:01:37.802] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Icon.9c9e50be.js            [39m[1m[2m 50.90 kB[22m[1m[22m[2m │ gzip:  17.68 kB[22m
[03:01:37.802] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/helpers.758c2c4b.js         [39m[1m[2m 78.28 kB[22m[1m[22m[2m │ gzip:  28.41 kB[22m
[03:01:37.802] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/0.d5921c45.js                [39m[1m[2m164.54 kB[22m[1m[22m[2m │ gzip:  50.36 kB[22m
[03:01:37.802] [2m.svelte-kit/output/client/[22m[36m_app/immutable/nodes/28.7fa1319a.js               [39m[1m[33m754.05 kB[39m[22m[2m │ gzip: 203.45 kB[22m
[03:01:37.802] [2m.svelte-kit/output/client/[22m[36m_app/immutable/chunks/Html.d72b56b5.js            [39m[1m[33m914.68 kB[39m[22m[2m │ gzip: 302.67 kB[22m
[03:01:37.802] [32m✓ built in 8.60s[39m
[03:01:37.802] [33m
[03:01:37.802] (!) Some chunks are larger than 500 kBs after minification. Consider:
[03:01:37.802] - Using dynamic import() to code-split the application
[03:01:37.802] - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
[03:01:37.802] - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.[39m
[03:01:38.283] ADAPTER:  STATIC  PRERENDER:  ALL
[03:02:26.388] CMS PARSE ERROR: For event page
[03:02:26.388]   Invalid URL
[03:02:26.388]   TypeError [ERR_INVALID_URL]: Invalid URL
[03:02:26.388]       at new NodeError (node:internal/errors:399:5)
[03:02:26.388]       at URL.onParseError (node:internal/url:566:9)
[03:02:26.389]       at new URL (node:internal/url:646:5)
[03:02:26.389]       at parseEventPage (file:///vercel/path0/.svelte-kit/output/server/chunks/parse_cms.js:478:31)
[03:02:26.389]       at load (file:///vercel/path0/.svelte-kit/output/server/entries/pages/__locale_locale__/_events_events_/_slug_/_page.server.js:40:10)
[03:02:26.389]       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[03:02:26.389]       at async load_server_data (file:///vercel/path0/.svelte-kit/output/server/index.js:516:18)
[03:02:26.389]       at async file:///vercel/path0/.svelte-kit/output/server/index.js:1872:18
[03:02:26.391]   {
[03:02:26.391]     Events: [
[03:02:26.391]       {
[03:02:26.391]         id: '19',
[03:02:26.391]         date: '2023-06-15',
[03:02:26.391]         start_time: '17:00:00',
[03:02:26.391]         end_time: '18:30:00',
[03:02:26.391]         registration_link: null,
[03:02:26.391]         target_group: 'general_public',
[03:02:26.391]         language: 'de-DE',
[03:02:26.391]         description: '<p style="text-align: justify;">In der <a href="https://www.uni-konstanz.de/adilt/ringvorlesung/" target="_blank" rel="noopener">Ringvorlesung</a> des Advanced Data and Information Literacy Track (ADILT) an der Universit&auml;t Konstanz stellt sich das Local Chapter CorrelAidX Konstanz traditionell vor, berichtet von aktuellen Projekten auf lokaler Ebene und hat dieses Mal <a href="https://karla-magazin.de/" target="_blank" rel="noopener">Karla Konstanz</a>, das gemeinn&uuml;tzige Online-Stadtmagazin aus Konstanz, als Projektpartner mitgebracht - es geht um die Zusammenarbeit bei verschiedenen datenjournalistischen Themen!</p>',
[03:02:26.391]         teaser: 'CorrelAidX Konstanz in der Ringvorlesung zum Advanced Data and Information Literacy Track (ADILT) an der Universität Konstanz - geöffnet für Studierende aller Fachrichtungen und als Einführungsveranstaltung mit Themenbeiträgen zu datenbasierten Methoden, Themen der Digitalisierung und Informationskompetenz aus Fach- und Praxisperspektiven.',
[03:02:26.391]         type: 'talk',
[03:02:26.391]         online: false,
[03:02:26.391]         title: 'Ringvorlesung ADILT | Uni Konstanz',
[03:02:26.391]         location: 'Konstanz',
[03:02:26.391]         tags: [Array],
[03:02:26.391]         local_chapters: [Array]
[03:02:26.392]       }
[03:02:26.392]     ]
[03:02:26.392]   }
[03:02:26.392] Error: Error while parsing CMS content
[03:02:26.392]     at reportParseError (file:///vercel/path0/.svelte-kit/output/server/chunks/parse_cms.js:354:11)
[03:02:26.392]     at parseEventPage (file:///vercel/path0/.svelte-kit/output/server/chunks/parse_cms.js:482:5)
[03:02:26.392]     at load (file:///vercel/path0/.svelte-kit/output/server/entries/pages/__locale_locale__/_events_events_/_slug_/_page.server.js:40:10)
[03:02:26.392]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[03:02:26.392]     at async load_server_data (file:///vercel/path0/.svelte-kit/output/server/index.js:516:18)
[03:02:26.392]     at async file:///vercel/path0/.svelte-kit/output/server/index.js:1872:18
[03:02:26.398] file:///vercel/path0/node_modules/@sveltejs/kit/src/core/config/options.js:206
[03:02:26.398] 						throw new Error(
[03:02:26.399] 						      ^
[03:02:26.399] 
[03:02:26.399] Error: 500 /veranstaltungen/ringvorlesung-sose23/ (linked from /veranstaltungen/ringvorlesung-sose23)
[03:02:26.399] To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
[03:02:26.399]     at file:///vercel/path0/node_modules/@sveltejs/kit/src/core/config/options.js:206:13
[03:02:26.399]     at file:///vercel/path0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:63:25
[03:02:26.399]     at save (file:///vercel/path0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:398:4)
[03:02:26.399]     at visit (file:///vercel/path0/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:235:3)
[03:02:26.399] 
[03:02:26.399] Node.js v18.15.0
[03:02:26.409] [31m[vite-plugin-sveltekit-compile] Failed with code 1[39m
[03:02:26.409] [32m✓ built in 1m 4s[39m
[03:02:26.409] [31merror during build:
[03:02:26.409] Error: Failed with code 1
[03:02:26.410]     at ChildProcess.<anonymous> (file:///vercel/path0/node_modules/@sveltejs/kit/src/utils/fork.js:68:13)
[03:02:26.410]     at ChildProcess.emit (node:events:513:28)
[03:02:26.410]     at ChildProcess._handle.onexit (node:internal/child_process:291:12)[39m
[03:02:26.439] Error: Command "npm run build" exited with 1
[03:02:26.780] Deployment completed
[03:02:26.669] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

**Comment by jstet** [comment]
this probably happens due to registration link being null
