### ISSUE TITLE
Add Partners Collection and Content

### ISSUE THREAD

**Issue by jstet** [CorrelAid/correlaid_website#563]
- [ ] Create Collection
- [ ] Add Content

**Comment by jstet** [comment]
```
TypeError: rawEntries is not iterable
    at Module.parseEntries (/home/jstet/Code/CorrelAid_Work/correlaid_org/src/lib/js/parse_cms.js:75:26)
    at load (/home/jstet/Code/CorrelAid_Work/correlaid_org/src/routes/[[locale=locale]]/[about=about]/[partners=partners]/+page.server.js:16:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.load_server_data (/home/jstet/Code/CorrelAid_Work/correlaid_org/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/home/jstet/Code/CorrelAid_Work/correlaid_org/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13)
TypeError: rawEntries is not iterable
    at Module.parseEntries (/home/jstet/Code/CorrelAid_Work/correlaid_org/src/lib/js/parse_cms.js:75:26)
    at load (/home/jstet/Code/CorrelAid_Work/correlaid_org/src/routes/[[locale=locale]]/[about=about]/[partners=partners]/+page.server.js:16:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.load_server_data (/home/jstet/Code/CorrelAid_Work/correlaid_org/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/home/jstet/Code/CorrelAid_Work/correlaid_org/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13)

```
